version: '3.8'

services:
  prefect_server:
    build:
      context: .
      dockerfile: Dockerfile.prefect_server
    container_name: prefect_server
    environment:
      PREFECT_HOME: /root/.prefect
      PREFECT_SERVER__DB__CONNECTION_URL: postgresql+psycopg2://postgres:${DEST_DB_PASS}@${DEST_DB_HOST}:${DEST_DB_PORT}/${DEST_DB_NAME}
    ports:
      - "4200:4200"
    command: ["prefect", "server", "start"]

  prefect_agent:
    build:
      context: .
      dockerfile: Dockerfile.prefect_agent
    container_name: prefect_agent
    depends_on:
      - prefect_server
    environment:
      PREFECT_HOME: /root/.prefect
      PREFECT_AGENT__CONN__CONNECTION_URL: postgresql+psycopg2://postgres:${DEST_DB_PASS}@${DEST_DB_HOST}:${DEST_DB_PORT}/${DEST_DB_NAME}
    command: ["prefect", "agent", "start", "-q", "default"]

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_app
    depends_on:
      - prefect_server
    ports:
      - "8501:8501"
    env_file:
      - .env
    command: ["streamlit", "run", "app.py"]