version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
#      POSTGRES_DB: ${DEST_DB_NAME}
      POSTGRES_USER: ${DEST_DB_USER}
      POSTGRES_PASSWORD: ${DEST_DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: .
    container_name: streamlit_app
    command: bash -c "python main.py && streamlit run app.py"
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge