FROM python:3.10-slim

# Install PostgreSQL development files (optional)
RUN apt-get update && \
    apt-get install -y \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy Prefect agent code
COPY . /app

# Define default command
CMD ["prefect", "agent", "start", "-q", "default"]